### ISSUE TITLE
list automations by last triggered

### ISSUE THREAD

**Issue by lolouk44** [gadgetchnnel/lovelace-home-feed-card#22]
Not an issue, more of a request for help.
I already have 1 feed set for my sensors so if something changes, I can see what sensor just changed. This is already a life saver as going to history just takes so long.
I'm trying to now display a feed of automations by last triggered as opposed to their state.
(Their state is just on all the time)
The last_triggered is an attribute.
I was hoping I'd find a way to not have to list each automation individually by using `states.automation | expand` or similar, but I'm stuck.

Are you able to provide some pointers please?

**Comment by gadgetchnnel** [comment]
@lolouk44 In the latest beta version (0.3.5b1) I have changed how automations are handled, so it works as follows:
* The last_triggered time is used as the timestamp
* Automations which have never been triggered are not displayed
* The state of automations which have been triggered is displayed as "Triggered"

This should cover the first part of your suggestion.

In order to automate this so you don't need to manually add every automation, you should be able to use the [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) card for this, for example:

```
type: 'custom:auto-entities'
card:
  type: 'custom:home-feed-card'
  title: Automations
filter:
  include:
    - domain: automation
```

**Comment by lolouk44** [comment]
Thanks. Would I use the "Dev" option in HACS or do I need a separate install completely to test this?

**Comment by gadgetchnnel** [comment]
@lolouk44 On the page for this plugin in HACS, just click on the the three dots menu (to the right of the plugin name) and select "Show beta" from the menu. You can then select beta versions from the versions drop-down to install them.

**Comment by lolouk44** [comment]
Thanks @gadgetchnnel, that looks great so far.
Had to reboot HA (I also applied an update of HACS so probably why) but then  it worked flawlessly
