### ISSUE TITLE
Cannot assign to read only property 'exclude_states' of object '#<Object>'

### ISSUE THREAD

**Issue by iptvcld** [gadgetchnnel/lovelace-home-feed-card#31]
Getting error: Cannot assign to read only property 'exclude_states' of object '#<Object>' after updating to Home Assistant 0.106.0

**Comment by gadgetchnnel** [comment]
The latest Beta release of the card should fix this. If you used HACS to install the card you may be better installing the update manually (download it from the Releases page) as the current stable version of HACS has an issue where it doesn't download all the files this card requires.

**Comment by iptvcld** [comment]
Just downloaded 0.3.9b3 from the release page and copied all the files into the HA folder - refreshed and still the same issue.

**Comment by gadgetchnnel** [comment]
@iptvcld Can you try a hard refresh in the browser? I sometimes that that (or even just a second regular refresh) is needed when I have manually updated the files.

**Comment by iptvcld** [comment]
yes; i have even tried incognito

**Comment by gadgetchnnel** [comment]
Where are you putting the files? If you use HACS normally the files would need to be under /config/www/community/lovelace-home-feed-card

If you don't use HACS, you may need to update the URL in your resources so it has lovelace-home-feed-card.js?v=0.3.9b3 so that it doesn't use the old cached version.

**Comment by iptvcld** [comment]
My HACS go to www\community\lovelace-home-feed-card and this path:

url: /local/community/lovelace-home-feed-card/lovelace-home-feed-card.js
type: js

I have made sure i put the downloaded files into the same path from 0.3.9b3

**Comment by gadgetchnnel** [comment]
@iptvcld I just realised something I forgot to mention. If there is a file named **lovelace-home-feed-card.js.gz** in the folder, you need to delete it. This is a compressed version of the file which is generated by HACS when it installed the card and, if you don't remove it, HACS will use that instead of the new file.

**Comment by iptvcld** [comment]
Thanks.. What i did was 
- fully uninstalled this addon from HACS
- create a new folder (lovelace-home-feed-card)
- dumped in your files from 0.3.9b3
- added ?v=0.3.9b3 to the lovelace addin line

= Worked..

**Comment by iptvcld** [comment]
Once this has been corrected to work HACS, would be good to know so i can convert back.. Thank you again for your support

**Comment by gadgetchnnel** [comment]
@iptvcld Can you please try the latest Beta 0.4.0b1? This has been refactored to work better with HACS as there is now only a single Javascript file to download.

**Comment by iptvcld** [comment]
i just installed 0.3.9 from master and that worked ok

**Comment by iptvcld** [comment]
also installed 0.4.0b2 and that worked as well

**Comment by gadgetchnnel** [comment]
Closing now as this appears to be resolved.
